version: '3.8'

services:

  backend:
    image: vizzbob/hms-backend:latest
    container_name: hms_backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - hms_network

  frontend:
    image: vizzbob/hms-frontend:latest
    container_name: hms_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - hms_network

  admin:
    image: vizzbob/hms-admin:latest
    container_name: hms_admin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - hms_network

networks:
  hms_network:
    driver: bridge
